import { useCallback, useEffect, useState } from "react";
import { api, ApiError } from "@/api/client";
import { Button } from "@/components/ui/button";
import { createRequestId } from "@/lib/requestId";

type Obj = Record<string, any>;
type Job = { id: string; key: string; state: string; error?: string; result: Obj; request: Obj };
const defaultCompileSkill = "viking://agent/skills/ontology-extraction-v1";
const root = "/te/enterprise/v1";
const tabs = ["来源", "领域包与 Schema", "构建", "候选评审", "发布版本", "使用反馈"];
const initialSchema = { revision: "draft-v1", entity_types: ["Document"], predicates: {}, rules: [], issue_pack_revision: "draft-v1", evidence_slots: [] };
const pretty = (v: unknown) => JSON.stringify(v, null, 2);
const errorHints: Record<string, string> = {
  COMPILE_SKILL_VERSION_MISMATCH: "OV 中的专用 Skill 与 TE 发布版本不一致，请安装随部署包提供的 ontology-extraction-v1。",
  COMPILE_WORKSPACE_NOT_PRIVATE: "编译工作区未通过权限检查，请检查 OV restricted ACL；尚不能提交编译。",
  COMPILE_IDENTITY_MUST_BE_SEPARATE: "ontology.compile_user 必须使用独立后端编译身份，不能与业务映射用户相同。",
  SCHEMA_PROPOSAL_CHANGED: "Schema 提案已变化，请重新打开任务核对。",
  COVERAGE_ACKNOWLEDGEMENT_REQUIRED: "请先阅读并勾选接受未覆盖资料，再批准发布。",

  BROWSER_RANDOM_UNAVAILABLE: "浏览器不支持生成请求标识，请使用新版浏览器后重试。构建请求尚未提交。",
  SOURCE_URI_IS_DIRECTORY: "填写的是目录。请使用来源集合入口递归冻结目录。",
  INVALID_ARGUMENT: "OV 拒绝了请求参数，请检查来源 URI 是否为可读取的正文文件，以及其他字段是否正确。",
  OV_NOT_FOUND: "OV 接口或来源不存在，请检查文件 URI 和 OV 部署版本。",
  NOT_FOUND: "OV 中未找到该来源，请检查文件 URI。",
  OV_VALIDATION_ERROR: "OV 请求字段校验失败，请检查输入及 TE／OV 契约版本。",
};

function Graph({ candidate }: { candidate: Obj }) {
  const nodes: Obj[] = candidate.entities || [];
  const assertions: Obj[] = candidate.assertions || [];
  const shown = nodes.slice(0, 30);
  const points = new Map(shown.map((n, i) => [n.entity_id, { x: 110 + (i % 4) * 210, y: 60 + Math.floor(i / 4) * 110 }]));
  return <div className="overflow-auto rounded border"><svg viewBox={`0 0 880 ${Math.max(180, Math.ceil(shown.length / 4) * 110 + 40)}`} role="img" aria-label="候选实体关系图">
    {assertions.filter(a => points.has(a.subject) && points.has(String(a.value))).map(a => {
      const from = points.get(a.subject)!; const to = points.get(String(a.value))!;
      return <g key={a.assertion_id}><line x1={from.x} y1={from.y} x2={to.x} y2={to.y} stroke="#64748b" /><text x={(from.x + to.x) / 2} y={(from.y + to.y) / 2 - 8} fontSize="12" fill="currentColor">{a.predicate}</text></g>;
    })}
    {shown.map(n => { const p = points.get(n.entity_id)!; return <g key={n.entity_id}><rect x={p.x - 90} y={p.y - 23} width="180" height="46" rx="10" fill="#eff6ff" stroke="#3b82f6" /><text x={p.x} y={p.y + 5} textAnchor="middle" fontSize="13" fill="#172554">{String(n.label || n.entity_id).slice(0, 22)}</text></g>; })}
  </svg>{nodes.length > 30 && <p className="p-2 text-sm">图中展示前 30 个实体，完整内容可在候选详情查看。</p>}</div>;
}

export default function OntologyView({ active, scope }: { active: boolean; scope: string }) {
  const [tab, setTab] = useState(0); const [jobs, setJobs] = useState<Job[]>([]); const [job, setJob] = useState<Job | null>(null);
  const [generation, setGeneration] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [collections, setCollections] = useState<Job[]>([]); const [collectionId, setCollectionId] = useState("");
  const [ackGaps, setAckGaps] = useState(false); const [mapping, setMapping] = useState("{}");
  const [skillUri, setSkillUri] = useState(""); const [defaultSkill, setDefaultSkill] = useState(defaultCompileSkill);
  const [pendingBuild, setPendingBuild] = useState<Obj | null>(null);
  const [schema, setSchema] = useState(pretty(initialSchema));
  const [sourceId, setSourceId] = useState(""); const [readers, setReaders] = useState(""); const [sources, setSources] = useState<Obj[]>([]);
  const [note, setNote] = useState(""); const [versions, setVersions] = useState<Obj[]>([]); const [feedback, setFeedback] = useState<Obj[]>([]);
  const [entity, setEntity] = useState(""); const [context, setContext] = useState<Obj | null>(null); const [edit, setEdit] = useState("");
  const [uri, setUri] = useState(""); const [accessSubject, setAccessSubject] = useState("");
  const [accessReceipt, setAccessReceipt] = useState<Obj | null>(null);
  const [permissionPreset, setPermissionPreset] = useState("agent"); const [withdrawal, setWithdrawal] = useState<Obj | null>(null);
  const [revision, setRevision] = useState(""); const [reviewPath, setReviewPath] = useState(""); const [reviewValue, setReviewValue] = useState("");
  const [compareId, setCompareId] = useState(""); const [comparison, setComparison] = useState<Obj | null>(null);
  const post = (path: string, body?: unknown) => api<Obj>(root + path, { method: "POST", headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined });
  const refresh = useCallback(async () => {
    const [list, caps, groups] = await Promise.all([api<Job[]>(root + "/jobs"), api<Obj>(root + "/capabilities"), api<Job[]>(root + "/source-collections")]);
    setCollections(groups); setDefaultSkill(caps.compile_skill_uri || defaultCompileSkill);
    setJobs(list); setGeneration(caps.generation);
    setJob(current => current ? list.find(j => j.id === current.id) || current : null);
  }, []);
  useEffect(() => { setSkillUri(sessionStorage.getItem(`ontology.compileSkill.v1:${scope}`) || ""); setDefaultSkill(defaultCompileSkill); try { setPendingBuild(JSON.parse(sessionStorage.getItem(`ontology.pendingBuild.compile.v1:${scope}`) || "null")); } catch { setPendingBuild(null); } setJob(null); setJobs([]); setSources([]); setCollections([]); setCollectionId(""); setAckGaps(false); setGeneration(0); setContext(null); setComparison(null); setVersions([]); setFeedback([]); setWithdrawal(null); setReviewPath(""); setError(""); setAccessReceipt(null); }, [scope]);
  useEffect(() => { if (!active) return; refresh().catch(e => setError(e.message)); const timer = setInterval(() => refresh().catch(() => {}), 5000); return () => clearInterval(timer); }, [active, scope, refresh]);
  const action = async (fn: () => Promise<void>) => { setBusy(true); setError(""); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } };
  const select = (value: Job) => { setJob(value); setEdit(pretty(value.result.candidate || {})); setAckGaps(false); setTab(value.state === "schema_review" ? 1 : 3); if (value.result.output?.schema) setSchema(pretty(value.result.output.schema)); setComparison(null); };
  const updateJob = async (path: string, body?: unknown) => { const value = await post(path, body) as Job; setJob(value); setEdit(pretty(value.result.candidate || {})); await refresh(); };
  const decision = (path: string, decision: string) => action(async () => { if (!job) return; await updateJob(`/jobs/${job.id}/review`, { path, decision, expected_digest: job.result.artifact.candidate_digest }); });
  const input = "rounded border bg-background p-2 text-sm";
  const collection = collections.find(c => c.id === collectionId);
  const candidate = job?.result.candidate || {};
  const pack = (candidate.schema_proposals || []).find((p: Obj) => p.kind === "domain_pack")?.annotated;
  return <div className="space-y-5 p-5">
    <header><h2 className="text-xl font-semibold">知识运营 · Ontology</h2><p className="text-sm text-muted-foreground">从来源到可追溯的领域知识。当前正式版本：{generation || "尚未发布"}。</p></header>
    <nav className="flex flex-wrap gap-2" aria-label="知识运营流程">{tabs.map((name, i) => <Button key={name} variant={tab === i ? "default" : "outline"} onClick={() => { setTab(i); if (i === 4) action(async () => setVersions((await api<Obj>(root + "/versions")).versions)); if (i === 5) action(async () => setFeedback(await api<Obj[]>(root + "/feedback"))); }}>{name}</Button>)}</nav>
    {error && <div role="alert" className="rounded border border-red-300 bg-red-50 p-3 text-red-800">{error}<p className="text-xs">{errorHints[error] || (/ONTOLOGY_DISABLED|FORBIDDEN|CONSOLE_ADMIN_REQUIRED/.test(error) ? "请检查当前 OV 账户的本体启用状态及用户授权。" : "操作未完成，请根据上方错误检查输入或服务状态。")}</p></div>}
    {tab === 0 && <section className="space-y-3 rounded-xl border p-4"><h3>添加与冻结来源</h3><p className="text-sm text-muted-foreground">支持 Viking 文件或 Wiki 目录递归冻结；本地上传支持 PDF、Word、Excel、Markdown、HTML 和文本。来源集合持久化保存，失败文件会明确列出。</p><p className="text-xs text-muted-foreground">来源标识用于区分文档，例如 policy-001；可读用户填写 OV 用户标识，需包含当前映射用户。</p>
      <div className="flex flex-wrap gap-3"><input className={input} aria-label="来源标识" placeholder="来源标识" value={sourceId} onChange={e => setSourceId(e.target.value)} /><input className={input} aria-label="可读用户" placeholder="可读用户，逗号分隔（包含自己）" value={readers} onChange={e => setReaders(e.target.value)} />
      <input type="file" aria-label="上传来源文档" disabled={busy || !sourceId || !readers} accept=".txt,.md,.markdown,.html,.htm,.pdf,.docx,.xlsx" onChange={e => { const file = e.target.files?.[0]; if (file) action(async () => {
        if (file.size > 5_000_000) throw new Error("文件超过 5MB，请拆分后上传");
        const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; for (const byte of bytes) binary += String.fromCharCode(byte);
        const ref = await post("/documents", { filename: file.name, source_id: sourceId, readers: readers.split(",").map(s => s.trim()).filter(Boolean), content_base64: btoa(binary) }); setSources(current => [...current, ref]);
      }); }} /></div>
      <div className="flex flex-wrap gap-3"><input className={input + " grow"} aria-label="Viking 来源 URI" placeholder="viking://resources/Wiki目录/ 或正文文件.md" value={uri} onChange={e => setUri(e.target.value)} /><Button disabled={busy || (!uri.trim() && !sources.length) || !readers} onClick={() => action(async () => {
        const key = `ontology.pendingSources.v1:${scope}`; let request = sessionStorage.getItem(key);
        if (!request) { request = JSON.stringify({ contract: "sf.te.ontology.sources.v1", submission_key: createRequestId(), roots: uri.trim() ? [uri.trim()] : [], references: sources, readers: readers.split(",").map(s => s.trim()).filter(Boolean) }); sessionStorage.setItem(key, request); }
        const group = await post("/source-collections", JSON.parse(request)) as Job; sessionStorage.removeItem(key); setCollectionId(group.id); setSources([]); await refresh();
      })}>创建并冻结来源集合</Button></div>
      {sources.map(s => <p key={s.digest} className="break-all text-sm">{s.source_id} · {s.revision} · 已冻结</p>)}
      <label className="block text-sm">选择已保存的来源集合<select aria-label="来源集合" className={input + " ml-2"} value={collectionId} onChange={e => setCollectionId(e.target.value)}><option value="">请选择</option>{collections.map(c => <option key={c.id} value={c.id}>{c.id} · {c.state} · {c.result.refs?.length || 0} 份资料</option>)}</select></label>
      {collection && <div className="space-y-2 text-sm"><p>阶段：{collection.result.stage || collection.state}；已冻结 {collection.result.refs?.length || 0}；缺口 {collection.result.gaps?.length || 0} {collection.error}</p><details><summary>文件及缺口</summary><pre className="max-h-72 overflow-auto">{pretty({ files: collection.result.files, gaps: collection.result.gaps })}</pre></details><Button disabled={busy || !["failed", "sources_ready"].includes(collection.state)} onClick={() => action(async () => { await post(`/source-collections/${collection.id}/retry`); await refresh(); })}>重试失败来源</Button><Button disabled={busy || collection.state === "cancelled"} onClick={() => action(async () => { await post(`/source-collections/${collection.id}/cancel`); await refresh(); })}>取消来源任务</Button></div>}
      <Button onClick={() => setTab(2)} disabled={collection?.state !== "sources_ready"}>使用这些来源构建</Button>
    </section>}
    {tab === 1 && <section className="space-y-3 rounded-xl border p-4"><h3>Schema 与领域包</h3>{job?.state === "schema_review" && <div className="space-y-2"><p>OV Compile 已生成 Schema 提案及事实草稿。确认未修改语义的 Schema 后直接转换，不再扫描原文。</p><details><summary>查看类型与关系的已核验证据定位</summary><p className="text-xs">每个概念最多列出三处来源位置。未列出的定义没有事实示例支持，需要人工核查。</p><pre className="max-h-64 overflow-auto text-xs">{pretty(job.result.schema_basis || {})}</pre></details><textarea aria-label="Schema 映射" className={input + " w-full font-mono"} value={mapping} onChange={e => setMapping(e.target.value)} /><p className="text-xs">可填写 type_mapping、predicate_mapping；语义变化可用 affected_sources 指定需补编译的来源 ID，未指定则全量重编译。</p><Button disabled={busy} onClick={() => action(async () => { await post(`/jobs/${job.id}/schema-confirm`, { ...JSON.parse(mapping), schema_body: JSON.parse(schema), expected_digest: job.result.output_digest }); await refresh(); setTab(2); })}>确认 Schema 并生成候选</Button></div>}<p className="text-sm text-muted-foreground">Schema 约束业务事实；构建生成的领域包提案在候选页逐项审核。领域包导出不等于正式发布。</p><textarea aria-label="Schema 定义" className={input + " min-h-72 w-full font-mono"} value={schema} onChange={e => setSchema(e.target.value)} /><Button disabled={busy || job?.state === "schema_review"} onClick={() => action(async () => { const body = JSON.parse(schema); await post("/schemas", body); })}>保存 Schema 版本</Button><div className="border-t pt-3"><label>导入 enhancer 历史领域包 <input type="file" accept=".json" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (file) action(async () => { if (file.size > 5_000_000) throw new Error("导入文件过大"); const value = await post("/imports", JSON.parse(await file.text())) as Job; await refresh(); select(value); }); }} /></label><p className="text-xs">使用 ontology_import.py 生成导入文件。历史记录只供参考，补齐来源并重新构建后才能发布。</p></div></section>}
    {tab === 2 && <section className="space-y-4 rounded-xl border p-4"><h3>构建任务</h3><label className="block space-y-1 text-sm"><span>编译 Skill URI（可选）</span><input aria-label="编译 Skill URI" className={input + " w-full"} placeholder={defaultSkill} value={pendingBuild ? (pendingBuild.skill_uri || "") : skillUri} disabled={busy || !!pendingBuild} onChange={e => { setSkillUri(e.target.value); sessionStorage.setItem(`ontology.compileSkill.v1:${scope}`, e.target.value); }} /></label><p className="break-all text-xs text-muted-foreground">留空使用默认：{defaultSkill}。指定目录须包含与 TE 配套的 SKILL.md，且编译身份可读。</p>{pendingBuild && <p className="text-sm">上次受理尚未确认；重试沿用原请求的来源集合和 Skill 路径。</p>}<div className="flex gap-3"><span className="text-sm">Schema 由 Compile 提议，人工确认。来源集合：{collectionId || "请先选择"}</span><Button disabled={busy || (!pendingBuild && collection?.state !== "sources_ready")} onClick={() => action(async () => {
      const storageKey = `ontology.pendingBuild.compile.v1:${scope}`; let request = sessionStorage.getItem(storageKey);
      if (!request) { request = JSON.stringify({ contract: "sf.te.ontology.compile.v1", submission_key: createRequestId(), collection_id: collectionId, expected_generation: generation, skill_uri: skillUri.trim() || defaultSkill }); sessionStorage.setItem(storageKey, request); }
      setPendingBuild(JSON.parse(request));
      try {
        const result = await post("/jobs", JSON.parse(request)) as Job; sessionStorage.removeItem(storageKey); setPendingBuild(null); await refresh(); select(result);
      } catch (e) {
        if (e instanceof ApiError && e.status && [400, 401, 403, 404, 422, 429].includes(e.status)) { sessionStorage.removeItem(storageKey); setPendingBuild(null); }
        throw e;
      }
    })}>开始 Compile／受理对账</Button></div>
      <table className="w-full text-left text-sm"><thead><tr><th>任务</th><th>状态</th><th>操作</th></tr></thead><tbody>{jobs.map(j => <tr key={j.id} className="border-t"><td className="py-3">{j.key}<p className="break-all text-xs text-muted-foreground">Skill：{j.result.skill_uri || j.request?.skill_uri || "服务默认"}</p></td><td>{j.state} · {j.result.stage}{j.result.remote_status && ` / OV: ${j.result.remote_status}`}{j.error && ` · ${errorHints[j.error] || j.error}`}{j.result.remote_error && ` · ${j.result.remote_error}`}</td><td><Button variant="outline" onClick={() => select(j)}>查看</Button>{["failed", "compile_unknown"].includes(j.state) && <Button disabled={busy} onClick={() => action(async () => { await post(`/jobs/${j.id}/retry`); await refresh(); })}>重试／对账</Button>}</td></tr>)}</tbody></table>
    </section>}
    {tab === 3 && <section className="space-y-4 rounded-xl border p-4">{!job ? <p>请先选择一个构建任务。</p> : <><h3>{job.key} · {job.state}</h3>{job.state === "imported" && <p>历史导入：尚未关联可核验来源，不具备正式发布条件。</p>}<p className="text-sm">Compile：{job.result.compile_id || "尚未受理"} · {job.result.remote_status} · {job.result.stage}</p><p className="text-xs">Token 用量：{job.result.token_usage ? pretty(job.result.token_usage) : "OV 尚未返回"}；缓存：{job.result.cache_hit ? "已复用" : "未复用"}</p>{job.result.gaps?.length > 0 && <div className="rounded border p-3"><p>部分覆盖：{job.result.gaps.length} 项缺口</p><pre className="max-h-48 overflow-auto text-xs">{pretty(job.result.gaps)}</pre><label><input type="checkbox" checked={ackGaps} onChange={e => setAckGaps(e.target.checked)} /> 我已审阅并接受上述未覆盖资料</label></div>}<Graph candidate={candidate} />
      <h4 className="font-medium">事实与证据</h4>{(candidate.assertions || []).map((a: Obj, i: number) => <article className="space-y-2 rounded border p-3" key={a.assertion_id}><p>{a.subject} · {a.predicate} · {String(a.value)} <span className="text-xs">({a.polarity} / {a.epistemic_kind})</span></p><p className="text-xs">有效期：{a.valid_from} — {a.valid_to || "未设结束"}；限定：{pretty(a.qualifiers)}</p>
      {(candidate.evidence || []).filter((e: Obj) => (a.support_sets || []).flat().includes(e.evidence_id)).map((e: Obj) => <blockquote key={e.evidence_id} className="border-l-2 pl-3 text-sm">{e.quote}<footer className="text-xs text-muted-foreground">{e.source_id} / {e.revision}，字符 {e.start}–{e.end}</footer></blockquote>)}
      <div className="flex gap-2"><Button disabled={busy} variant="outline" onClick={() => decision(`assertions.${i}`, "approve")}>批准此项</Button><Button disabled={busy} variant="outline" onClick={() => decision(`assertions.${i}`, "reject")}>驳除此项</Button><Button variant="outline" disabled={busy} onClick={() => { setReviewPath(`assertions.${i}`); setReviewValue(pretty(a)); }}>编辑此项</Button><span className="text-sm">{candidate.extraction?.reviews?.[a.assertion_id]?.decision || "待评审"}</span></div></article>)}
      {pack && <section className="space-y-2"><h4>领域包逐项评审</h4><Graph candidate={{ entities: (pack.pack.concepts || []).map((c: Obj) => ({ entity_id: c.id, label: c.name })), assertions: (pack.pack.relations || []).map((r: Obj) => ({ assertion_id: r.id, subject: r.subject, predicate: r.predicate, value: r.object })) }} />{Object.entries(pack.meta || {}).map(([path, meta]) => <div key={path} className="flex items-center gap-3 border-b py-2"><details className="grow"><summary>{path} · {(meta as Obj).status}</summary><pre className="overflow-auto text-xs">{pretty(path.split(".").reduce((v: any, k) => v?.[k], pack.pack))}</pre><pre className="overflow-auto text-xs">{pretty(pack.evidence?.[path] || [])}</pre></details><Button variant="outline" disabled={busy} onClick={() => decision(path, "approve")}>批准</Button><Button variant="outline" disabled={busy} onClick={() => decision(path, "reject")}>驳回</Button><Button variant="outline" disabled={busy || !job.result.artifact} onClick={() => { setReviewPath(path); setReviewValue(pretty(path.split(".").reduce((v: any, k) => v?.[k], pack.pack))); }}>编辑</Button></div>)}<Button onClick={() => action(async () => { const exported = await api<Obj>(`${root}/jobs/${job.id}/export`); const url = URL.createObjectURL(new Blob([pretty(exported)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `${job.id}-domain-pack.json`; link.click(); URL.revokeObjectURL(url); })}>导出已评审领域包</Button></section>}
      {reviewPath && <div className="space-y-2 rounded border p-3"><p>编辑 {reviewPath}</p><textarea aria-label="逐项编辑" className={input + " min-h-48 w-full font-mono"} value={reviewValue} onChange={e => setReviewValue(e.target.value)} /><Button disabled={busy} onClick={() => action(async () => { await updateJob(`/jobs/${job.id}/review`, { path: reviewPath, decision: "edit", edited_value: JSON.parse(reviewValue), expected_digest: job.result.artifact.candidate_digest }); setReviewPath(""); })}>保存此项并重新校验</Button><Button variant="outline" onClick={() => setReviewPath("")}>关闭</Button></div>}
      <details><summary>编辑候选内容（保存后需要重新审核与批准）</summary><textarea className={input + " min-h-72 w-full font-mono"} aria-label="候选编辑" value={edit} onChange={e => setEdit(e.target.value)} /><Button disabled={busy || !job.result.artifact} onClick={() => action(async () => { const value = await api<Job>(`${root}/jobs/${job.id}/candidate`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ candidate: JSON.parse(edit), expected_digest: job.result.artifact.candidate_digest }) }); select(value); await refresh(); })}>保存并重新校验</Button></details>
      <textarea className={input + " w-full"} aria-label="审核意见" placeholder="记录审核依据" value={note} onChange={e => setNote(e.target.value)} />
      <div className="flex flex-wrap gap-2"><Button disabled={busy || !["review_ready","prepared"].includes(job.state)} onClick={() => action(() => updateJob(`/jobs/${job.id}/prepare`))}>校验并准备发布</Button><Button disabled={busy || job.state !== "prepared" || !note.trim()} onClick={() => action(() => updateJob(`/jobs/${job.id}/approve`, { note, acknowledge_gaps: ackGaps }))}>批准发布</Button><Button disabled={busy || !["approved","publishing","commit_unknown"].includes(job.state)} onClick={() => action(() => updateJob(`/jobs/${job.id}/commit`, { commit_key: job.result.commit_key || `${job.id}:${job.result.prepared.prepared_id}` }))}>发布／回执对账</Button><Button variant="outline" disabled={busy || ["published","publishing","commit_unknown"].includes(job.state)} onClick={() => action(() => updateJob(`/jobs/${job.id}/cancel`))}>取消任务</Button><Button variant="outline" disabled={busy || job.state === "imported"} onClick={() => action(async () => { const value = await post(`/jobs/${job.id}/rebase`, { submission_key: `${job.id}:rebase:${generation}` }) as Job; await refresh(); select(value); })}>基于当前版本重新构建</Button></div>
      {job.result.receipt && <pre className="overflow-auto rounded bg-muted p-3 text-xs">{pretty(job.result.receipt)}</pre>}
      <div className="flex gap-2"><select className={input} aria-label="比较任务" value={compareId} onChange={e => setCompareId(e.target.value)}><option value="">选择比较版本</option>{jobs.filter(j => j.id !== job.id && j.result.candidate).map(j => <option key={j.id} value={j.id}>{j.key}</option>)}</select><Button disabled={!compareId} onClick={() => action(async () => setComparison(await api<Obj>(`${root}/jobs/${compareId}/compare/${job.id}`)))}>查看差异</Button></div>{comparison && <pre className="overflow-auto text-xs">{pretty(comparison)}</pre>}
    </>}</section>}
    {tab === 4 && <section className="space-y-3 rounded-xl border p-4"><h3>正式发布版本</h3>{versions.length ? versions.map(v => <div key={v.receipt_id} className="rounded border p-3">版本 {v.generation} · {v.committed_at}<p className="text-xs">回执 {v.receipt_id}</p><Button variant="outline" disabled={busy} onClick={() => action(async () => { const value = await post("/rollback-candidates", { generation: v.generation, submission_key: `rollback:${v.generation}:base:${generation}` }) as Job; await refresh(); select(value); })}>生成回滚候选</Button></div>) : <p>尚无发布回执。</p>}<div className="flex gap-2"><input className={input} aria-label="诊断实体" value={entity} onChange={e => setEntity(e.target.value)} placeholder="实体 ID" /><Button disabled={!entity || busy} onClick={() => action(async () => setContext(await post("/context/compose", { entity_ids: [entity], token_budget: 4000 })))}>查看事实、冲突与缺口</Button></div><div className="space-y-2 border-t pt-3"><h4>撤回来源</h4><p className="text-xs">按来源版本阻断依赖事实的访问。收到 OV 回执前保持处理中。</p><input className={input} aria-label="撤回来源" placeholder="来源 ID" value={sourceId} onChange={e => setSourceId(e.target.value)} /><input className={input} aria-label="撤回版本" placeholder="来源 revision" value={revision} onChange={e => setRevision(e.target.value)} /><Button disabled={busy || !sourceId || !revision} onClick={() => action(async () => { setWithdrawal({ state: "撤回处理中" }); const result = await post("/source-events", { event_id: `withdraw:${sourceId}:${revision}`, source_id: sourceId, revision, status: "revoked" }); setWithdrawal({ state: "已收到撤回回执", receipt: result }); })}>撤回／按键对账</Button>{withdrawal && <pre className="overflow-auto text-xs">{pretty(withdrawal)}</pre>}</div>{context && <pre className="overflow-auto text-xs">{pretty(context)}</pre>}</section>}
    {tab === 5 && <section className="space-y-3 rounded-xl border p-4"><h3>Agent 权限与反馈</h3><div className="flex flex-wrap gap-2"><input className={input} aria-label="OV 用户标识" placeholder="OV 用户标识（例如 frank）" value={accessSubject} onChange={e => setAccessSubject(e.target.value)} /><select className={input} aria-label="权限模板" value={permissionPreset} onChange={e => setPermissionPreset(e.target.value)}><option value="agent">Agent：读取与反馈</option><option value="operator">运营：构建、审批、发布与读取</option><option value="disabled">停用此用户</option></select><Button disabled={busy || !accessSubject} onClick={() => action(async () => { setAccessReceipt(null); const receipt = await api<Obj>(root + "/access", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject: accessSubject, active: permissionPreset !== "disabled", enabled: true, permissions: permissionPreset === "operator" ? ["build","approve","publish","read","feedback"] : ["read","feedback"] }) }); setAccessReceipt(receipt); await refresh(); })}>保存 OV 授权</Button></div>{accessReceipt && <p role="status" className="text-sm">已保存 OV 授权：账户 {accessReceipt.account}，用户 {accessReceipt.subject}（{accessReceipt.active ? "启用" : "停用"}）。</p>}<p className="text-sm text-muted-foreground">反馈进入运营评审，不自动修改正式事实。</p>{feedback.length ? feedback.map(f => <article key={f.id} className="rounded border p-3"><p>{f.body.note}</p><p className="text-xs">{f.body.result_ref} · {f.created_at}</p></article>) : <p>暂无反馈。</p>}</section>}
  </div>;
}
